package com.junpeng.daigou.dao;

import com.junpeng.daigou.model.Attribute;
import com.junpeng.daigou.model.AttributeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int countByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int deleteByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idattribute);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int insert(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int insertSelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    List<Attribute> selectByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    Attribute selectByPrimaryKey(Integer idattribute);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Attribute record);
    
    List<Attribute> selectAttributeByProductId(@Param("idcategory") int idcategory , @Param("idproduct") int idproduct);
}