package com.junpeng.daigou.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.junpeng.daigou.model.DiscountSetting;
import com.junpeng.daigou.model.DiscountSettingExample;

@Mapper
public interface DiscountSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int countByExample(DiscountSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int deleteByExample(DiscountSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer iddiscountsetting);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int insert(DiscountSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int insertSelective(DiscountSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    List<DiscountSetting> selectByExample(DiscountSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    DiscountSetting selectByPrimaryKey(Integer iddiscountsetting);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DiscountSetting record, @Param("example") DiscountSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DiscountSetting record, @Param("example") DiscountSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiscountSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discountsetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiscountSetting record);
}