package com.junpeng.daigou.dao;

import com.junpeng.daigou.model.OrderDetail;
import com.junpeng.daigou.model.OrderTable;
import com.junpeng.daigou.model.OrderTableExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int countByExample(OrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int deleteByExample(OrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idorder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int insert(OrderTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int insertSelective(OrderTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    List<OrderTable> selectByExample(OrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    OrderTable selectByPrimaryKey(Integer idorder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderTable record, @Param("example") OrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderTable record, @Param("example") OrderTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordertable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTable record);
    
    List<OrderTable> getOrderByCustomerAndStatus(@Param("idcustomer") int idcustomer , @Param("status")  String status, @Param("idorder")  int idorder);

	List<OrderDetail> getOrderByOrderId(@Param("idorder") int idorder , @Param("idorderdetail") int idorderdetail ,@Param("idcustomer") int idcustomer, @Param("status") String status,@Param("idproduct") int idproduct);
	
	int udpateSumprofit(@Param("idorder") int idorder);
	
	int updateSumprice(@Param("idorder") int idorder);
}