package com.junpeng.daigou.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.junpeng.daigou.model.Purchase;
import com.junpeng.daigou.model.PurchaseDetail;
import com.junpeng.daigou.model.PurchaseExample;
import com.junpeng.daigou.model.PurchasingProduct;

@Mapper
public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int countByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int deleteByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idpurchase);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int insertSelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    List<Purchase> selectByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    Purchase selectByPrimaryKey(Integer idpurchase);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Purchase record, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Purchase record, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Purchase record);

	List<PurchaseDetail> getPurchaseByPurchaseId(@Param("purchaseId") Integer purchaseId,@Param("productId") Integer productId,@Param("marketId") Integer marketId,@Param("brandId") Integer brandId, @Param("purchaseDetailId") Integer purchaseDetailId);

	List<Purchase> getPurchaseByBrandOrDate(@Param("marketId") Integer marketId, @Param("startDate") Date startDate , @Param("idpurchase") Integer idpurchase);
	
	List<PurchasingProduct> getProductGroupByStatusForCount();
}