package com.junpeng.daigou.dao;

import com.junpeng.daigou.model.PurchaseDetail;
import com.junpeng.daigou.model.PurchaseDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PurchaseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int countByExample(PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int deleteByExample(PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idpurchasedetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int insert(PurchaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int insertSelective(PurchaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    List<PurchaseDetail> selectByExample(PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    PurchaseDetail selectByPrimaryKey(Integer idpurchasedetail);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PurchaseDetail record, @Param("example") PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PurchaseDetail record, @Param("example") PurchaseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PurchaseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PurchaseDetail record);
}