package com.junpeng.daigou.dao;

import com.junpeng.daigou.model.SystemSetting;
import com.junpeng.daigou.model.SystemSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int countByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int deleteByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idsystemsetting);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int insert(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int insertSelective(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    List<SystemSetting> selectByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    SystemSetting selectByPrimaryKey(Integer idsystemsetting);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemSetting record);
}