package com.junpeng.daigou.model;

import java.util.Date;

public class AttributeDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.idattributedefine
     *
     * @mbggenerated
     */
    private Integer idattributedefine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.idcategory
     *
     * @mbggenerated
     */
    private Integer idcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.attributename
     *
     * @mbggenerated
     */
    private String attributename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.createuser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.updateuser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attributedefine.isactive
     *
     * @mbggenerated
     */
    private String isactive;
    
    private String categoryname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.idattributedefine
     *
     * @return the value of attributedefine.idattributedefine
     *
     * @mbggenerated
     */
    public Integer getIdattributedefine() {
        return idattributedefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.idattributedefine
     *
     * @param idattributedefine the value for attributedefine.idattributedefine
     *
     * @mbggenerated
     */
    public void setIdattributedefine(Integer idattributedefine) {
        this.idattributedefine = idattributedefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.idcategory
     *
     * @return the value of attributedefine.idcategory
     *
     * @mbggenerated
     */
    public Integer getIdcategory() {
        return idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.idcategory
     *
     * @param idcategory the value for attributedefine.idcategory
     *
     * @mbggenerated
     */
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.attributename
     *
     * @return the value of attributedefine.attributename
     *
     * @mbggenerated
     */
    public String getAttributename() {
        return attributename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.attributename
     *
     * @param attributename the value for attributedefine.attributename
     *
     * @mbggenerated
     */
    public void setAttributename(String attributename) {
        this.attributename = attributename == null ? null : attributename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.createtime
     *
     * @return the value of attributedefine.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.createtime
     *
     * @param createtime the value for attributedefine.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.createuser
     *
     * @return the value of attributedefine.createuser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.createuser
     *
     * @param createuser the value for attributedefine.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.updatetime
     *
     * @return the value of attributedefine.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.updatetime
     *
     * @param updatetime the value for attributedefine.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.updateuser
     *
     * @return the value of attributedefine.updateuser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.updateuser
     *
     * @param updateuser the value for attributedefine.updateuser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attributedefine.isactive
     *
     * @return the value of attributedefine.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attributedefine.isactive
     *
     * @param isactive the value for attributedefine.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

	public String getCategoryname() {
		return categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}
    
    
}