package com.junpeng.daigou.model;

import java.util.Date;

public class Attribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.idattribute
     *
     * @mbggenerated
     */
    private Integer idattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.idproduct
     *
     * @mbggenerated
     */
    private Integer idproduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.idattributedefine
     *
     * @mbggenerated
     */
    private Integer idattributedefine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.createuser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.updateuser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.isactive
     *
     * @mbggenerated
     */
    private String isactive;
    
    private String attributename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.idattribute
     *
     * @return the value of attribute.idattribute
     *
     * @mbggenerated
     */
    public Integer getIdattribute() {
        return idattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.idattribute
     *
     * @param idattribute the value for attribute.idattribute
     *
     * @mbggenerated
     */
    public void setIdattribute(Integer idattribute) {
        this.idattribute = idattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.idproduct
     *
     * @return the value of attribute.idproduct
     *
     * @mbggenerated
     */
    public Integer getIdproduct() {
        return idproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.idproduct
     *
     * @param idproduct the value for attribute.idproduct
     *
     * @mbggenerated
     */
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.idattributedefine
     *
     * @return the value of attribute.idattributedefine
     *
     * @mbggenerated
     */
    public Integer getIdattributedefine() {
        return idattributedefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.idattributedefine
     *
     * @param idattributedefine the value for attribute.idattributedefine
     *
     * @mbggenerated
     */
    public void setIdattributedefine(Integer idattributedefine) {
        this.idattributedefine = idattributedefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.value
     *
     * @return the value of attribute.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.value
     *
     * @param value the value for attribute.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.createtime
     *
     * @return the value of attribute.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.createtime
     *
     * @param createtime the value for attribute.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.createuser
     *
     * @return the value of attribute.createuser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.createuser
     *
     * @param createuser the value for attribute.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.updatetime
     *
     * @return the value of attribute.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.updatetime
     *
     * @param updatetime the value for attribute.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.updateuser
     *
     * @return the value of attribute.updateuser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.updateuser
     *
     * @param updateuser the value for attribute.updateuser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.isactive
     *
     * @return the value of attribute.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.isactive
     *
     * @param isactive the value for attribute.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

	public String getAttributename() {
		return attributename;
	}

	public void setAttributename(String attributename) {
		this.attributename = attributename;
	}
    
    
}