package com.junpeng.daigou.model;

import java.util.Date;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.idbrand
     *
     * @mbggenerated
     */
    private Integer idbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brandName
     *
     * @mbggenerated
     */
    private String brandname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.createuser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.updateuser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.idbrand
     *
     * @return the value of brand.idbrand
     *
     * @mbggenerated
     */
    public Integer getIdbrand() {
        return idbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.idbrand
     *
     * @param idbrand the value for brand.idbrand
     *
     * @mbggenerated
     */
    public void setIdbrand(Integer idbrand) {
        this.idbrand = idbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brandName
     *
     * @return the value of brand.brandName
     *
     * @mbggenerated
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brandName
     *
     * @param brandname the value for brand.brandName
     *
     * @mbggenerated
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.type
     *
     * @return the value of brand.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.type
     *
     * @param type the value for brand.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.url
     *
     * @return the value of brand.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.url
     *
     * @param url the value for brand.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.createtime
     *
     * @return the value of brand.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.createtime
     *
     * @param createtime the value for brand.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.createuser
     *
     * @return the value of brand.createuser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.createuser
     *
     * @param createuser the value for brand.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.updatetime
     *
     * @return the value of brand.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.updatetime
     *
     * @param updatetime the value for brand.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.updateuser
     *
     * @return the value of brand.updateuser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.updateuser
     *
     * @param updateuser the value for brand.updateuser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.isactive
     *
     * @return the value of brand.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.isactive
     *
     * @param isactive the value for brand.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

}