package com.junpeng.daigou.model;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.idcategory
     *
     * @mbggenerated
     */
    private Integer idcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.categoryname
     *
     * @mbggenerated
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.createuser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.updateuser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.idcategory
     *
     * @return the value of category.idcategory
     *
     * @mbggenerated
     */
    public Integer getIdcategory() {
        return idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.idcategory
     *
     * @param idcategory the value for category.idcategory
     *
     * @mbggenerated
     */
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.categoryname
     *
     * @return the value of category.categoryname
     *
     * @mbggenerated
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.categoryname
     *
     * @param categoryname the value for category.categoryname
     *
     * @mbggenerated
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.createtime
     *
     * @return the value of category.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.createtime
     *
     * @param createtime the value for category.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.createuser
     *
     * @return the value of category.createuser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.createuser
     *
     * @param createuser the value for category.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.updatetime
     *
     * @return the value of category.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.updatetime
     *
     * @param updatetime the value for category.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.updateuser
     *
     * @return the value of category.updateuser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.updateuser
     *
     * @param updateuser the value for category.updateuser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.isactive
     *
     * @return the value of category.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.isactive
     *
     * @param isactive the value for category.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }
}