package com.junpeng.daigou.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.idcustomer
     *
     * @mbggenerated
     */
    private Integer idcustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customername
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.WXID
     *
     * @mbggenerated
     */
    private String wxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.wxname
     *
     * @mbggenerated
     */
    private String wxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.tbname
     *
     * @mbggenerated
     */
    private String tbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.alipayname
     *
     * @mbggenerated
     */
    private String alipayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.recommender
     *
     * @mbggenerated
     */
    private String recommender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address2
     *
     * @mbggenerated
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address3
     *
     * @mbggenerated
     */
    private String address3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.credit
     *
     * @mbggenerated
     */
    private String credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.idcustomer
     *
     * @return the value of customer.idcustomer
     *
     * @mbggenerated
     */
    public Integer getIdcustomer() {
        return idcustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.idcustomer
     *
     * @param idcustomer the value for customer.idcustomer
     *
     * @mbggenerated
     */
    public void setIdcustomer(Integer idcustomer) {
        this.idcustomer = idcustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customername
     *
     * @return the value of customer.customername
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customername
     *
     * @param customername the value for customer.customername
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.WXID
     *
     * @return the value of customer.WXID
     *
     * @mbggenerated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.WXID
     *
     * @param wxid the value for customer.WXID
     *
     * @mbggenerated
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.wxname
     *
     * @return the value of customer.wxname
     *
     * @mbggenerated
     */
    public String getWxname() {
        return wxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.wxname
     *
     * @param wxname the value for customer.wxname
     *
     * @mbggenerated
     */
    public void setWxname(String wxname) {
        this.wxname = wxname == null ? null : wxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.tbname
     *
     * @return the value of customer.tbname
     *
     * @mbggenerated
     */
    public String getTbname() {
        return tbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.tbname
     *
     * @param tbname the value for customer.tbname
     *
     * @mbggenerated
     */
    public void setTbname(String tbname) {
        this.tbname = tbname == null ? null : tbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.alipayname
     *
     * @return the value of customer.alipayname
     *
     * @mbggenerated
     */
    public String getAlipayname() {
        return alipayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.alipayname
     *
     * @param alipayname the value for customer.alipayname
     *
     * @mbggenerated
     */
    public void setAlipayname(String alipayname) {
        this.alipayname = alipayname == null ? null : alipayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.recommender
     *
     * @return the value of customer.recommender
     *
     * @mbggenerated
     */
    public String getRecommender() {
        return recommender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.recommender
     *
     * @param recommender the value for customer.recommender
     *
     * @mbggenerated
     */
    public void setRecommender(String recommender) {
        this.recommender = recommender == null ? null : recommender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address2
     *
     * @return the value of customer.address2
     *
     * @mbggenerated
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address2
     *
     * @param address2 the value for customer.address2
     *
     * @mbggenerated
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address3
     *
     * @return the value of customer.address3
     *
     * @mbggenerated
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address3
     *
     * @param address3 the value for customer.address3
     *
     * @mbggenerated
     */
    public void setAddress3(String address3) {
        this.address3 = address3 == null ? null : address3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.credit
     *
     * @return the value of customer.credit
     *
     * @mbggenerated
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.credit
     *
     * @param credit the value for customer.credit
     *
     * @mbggenerated
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.comment
     *
     * @return the value of customer.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.comment
     *
     * @param comment the value for customer.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}