package com.junpeng.daigou.model;

public class DiscountSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discountsetting.iddiscountsetting
     *
     * @mbggenerated
     */
    private Integer iddiscountsetting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discountsetting.discountsettingname
     *
     * @mbggenerated
     */
    private String discountsettingname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discountsetting.discountsettingcomment
     *
     * @mbggenerated
     */
    private String discountsettingcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discountsetting.discount
     *
     * @mbggenerated
     */
    private Double discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discountsetting.iddiscountsetting
     *
     * @return the value of discountsetting.iddiscountsetting
     *
     * @mbggenerated
     */
    public Integer getIddiscountsetting() {
        return iddiscountsetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discountsetting.iddiscountsetting
     *
     * @param iddiscountsetting the value for discountsetting.iddiscountsetting
     *
     * @mbggenerated
     */
    public void setIddiscountsetting(Integer iddiscountsetting) {
        this.iddiscountsetting = iddiscountsetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discountsetting.discountsettingname
     *
     * @return the value of discountsetting.discountsettingname
     *
     * @mbggenerated
     */
    public String getDiscountsettingname() {
        return discountsettingname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discountsetting.discountsettingname
     *
     * @param discountsettingname the value for discountsetting.discountsettingname
     *
     * @mbggenerated
     */
    public void setDiscountsettingname(String discountsettingname) {
        this.discountsettingname = discountsettingname == null ? null : discountsettingname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discountsetting.discountsettingcomment
     *
     * @return the value of discountsetting.discountsettingcomment
     *
     * @mbggenerated
     */
    public String getDiscountsettingcomment() {
        return discountsettingcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discountsetting.discountsettingcomment
     *
     * @param discountsettingcomment the value for discountsetting.discountsettingcomment
     *
     * @mbggenerated
     */
    public void setDiscountsettingcomment(String discountsettingcomment) {
        this.discountsettingcomment = discountsettingcomment == null ? null : discountsettingcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discountsetting.discount
     *
     * @return the value of discountsetting.discount
     *
     * @mbggenerated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discountsetting.discount
     *
     * @param discount the value for discountsetting.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
}