package com.junpeng.daigou.model;

import java.util.Date;

public class OrderTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.idorder
     *
     * @mbggenerated
     */
    private Integer idorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.idcustomer
     *
     * @mbggenerated
     */
    private Integer idcustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.bookdate
     *
     * @mbggenerated
     */
    private Date bookdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.deposit
     *
     * @mbggenerated
     */
    private Double deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.payment
     *
     * @mbggenerated
     */
    private Double payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.deposittype
     *
     * @mbggenerated
     */
    private String deposittype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.paymenttype
     *
     * @mbggenerated
     */
    private String paymenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.postprice
     *
     * @mbggenerated
     */
    private Double postprice;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.remaindprice
     *
     * @mbggenerated
     */
    private Double remaindprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.sumprofit
     *
     * @mbggenerated
     */
    private Double sumprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.sumprice
     *
     * @mbggenerated
     */
    private Double sumprice;

    /**
    
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ordertable.status
     *
     * @mbggenerated
     */
    private String status;
    
    private String customerName;
    
    private String wxid;
    
    private String statusStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.idorder
     *
     * @return the value of ordertable.idorder
     *
     * @mbggenerated
     */
    public Integer getIdorder() {
        return idorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.idorder
     *
     * @param idorder the value for ordertable.idorder
     *
     * @mbggenerated
     */
    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.idcustomer
     *
     * @return the value of ordertable.idcustomer
     *
     * @mbggenerated
     */
    public Integer getIdcustomer() {
        return idcustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.idcustomer
     *
     * @param idcustomer the value for ordertable.idcustomer
     *
     * @mbggenerated
     */
    public void setIdcustomer(Integer idcustomer) {
        this.idcustomer = idcustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.bookdate
     *
     * @return the value of ordertable.bookdate
     *
     * @mbggenerated
     */
    public Date getBookdate() {
        return bookdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.bookdate
     *
     * @param bookdate the value for ordertable.bookdate
     *
     * @mbggenerated
     */
    public void setBookdate(Date bookdate) {
        this.bookdate = bookdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.deposit
     *
     * @return the value of ordertable.deposit
     *
     * @mbggenerated
     */
    public Double getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.deposit
     *
     * @param deposit the value for ordertable.deposit
     *
     * @mbggenerated
     */
    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.payment
     *
     * @return the value of ordertable.payment
     *
     * @mbggenerated
     */
    public Double getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.payment
     *
     * @param payment the value for ordertable.payment
     *
     * @mbggenerated
     */
    public void setPayment(Double payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.deposittype
     *
     * @return the value of ordertable.deposittype
     *
     * @mbggenerated
     */
    public String getDeposittype() {
        return deposittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.deposittype
     *
     * @param deposittype the value for ordertable.deposittype
     *
     * @mbggenerated
     */
    public void setDeposittype(String deposittype) {
        this.deposittype = deposittype == null ? null : deposittype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.paymenttype
     *
     * @return the value of ordertable.paymenttype
     *
     * @mbggenerated
     */
    public String getPaymenttype() {
        return paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.paymenttype
     *
     * @param paymenttype the value for ordertable.paymenttype
     *
     * @mbggenerated
     */
    public void setPaymenttype(String paymenttype) {
        this.paymenttype = paymenttype == null ? null : paymenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.postprice
     *
     * @return the value of ordertable.postprice
     *
     * @mbggenerated
     */
    public Double getPostprice() {
        return postprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.postprice
     *
     * @param postprice the value for ordertable.postprice
     *
     * @mbggenerated
     */
    public void setPostprice(Double postprice) {
        this.postprice = postprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.remaindprice
     *
     * @return the value of ordertable.remaindprice
     *
     * @mbggenerated
     */
    public Double getRemaindprice() {
        return remaindprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.remaindprice
     *
     * @param remaindprice the value for ordertable.remaindprice
     *
     * @mbggenerated
     */
    public void setRemaindprice(Double remaindprice) {
        this.remaindprice = remaindprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.sumprofit
     *
     * @return the value of ordertable.sumprofit
     *
     * @mbggenerated
     */
    public Double getSumprofit() {
        return sumprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.sumprofit
     *
     * @param sumprofit the value for ordertable.sumprofit
     *
     * @mbggenerated
     */
    public void setSumprofit(Double sumprofit) {
        this.sumprofit = sumprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.sumprice
     *
     * @return the value of ordertable.sumprice
     *
     * @mbggenerated
     */
    public Double getSumprice() {
        return sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.sumprice
     *
     * @param sumprice the value for ordertable.sumprice
     *
     * @mbggenerated
     */
    public void setSumprice(Double sumprice) {
        this.sumprice = sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ordertable.status
     *
     * @return the value of ordertable.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ordertable.status
     *
     * @param status the value for ordertable.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	
	public String getWxid() {
		return wxid;
	}

	public void setWxid(String wxid) {
		this.wxid = wxid;
	}

	public String getStatusStr() {
		return statusStr;
	}

	public void setStatusStr(String statusStr) {
		this.statusStr = statusStr;
	}
	
}