package com.junpeng.daigou.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public OrderDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdorderdetailIsNull() {
            addCriterion("idorderdetail is null");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailIsNotNull() {
            addCriterion("idorderdetail is not null");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailEqualTo(Integer value) {
            addCriterion("idorderdetail =", value, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailNotEqualTo(Integer value) {
            addCriterion("idorderdetail <>", value, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailGreaterThan(Integer value) {
            addCriterion("idorderdetail >", value, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailGreaterThanOrEqualTo(Integer value) {
            addCriterion("idorderdetail >=", value, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailLessThan(Integer value) {
            addCriterion("idorderdetail <", value, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailLessThanOrEqualTo(Integer value) {
            addCriterion("idorderdetail <=", value, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailIn(List<Integer> values) {
            addCriterion("idorderdetail in", values, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailNotIn(List<Integer> values) {
            addCriterion("idorderdetail not in", values, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailBetween(Integer value1, Integer value2) {
            addCriterion("idorderdetail between", value1, value2, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderdetailNotBetween(Integer value1, Integer value2) {
            addCriterion("idorderdetail not between", value1, value2, "idorderdetail");
            return (Criteria) this;
        }

        public Criteria andIdorderIsNull() {
            addCriterion("idorder is null");
            return (Criteria) this;
        }

        public Criteria andIdorderIsNotNull() {
            addCriterion("idorder is not null");
            return (Criteria) this;
        }

        public Criteria andIdorderEqualTo(Integer value) {
            addCriterion("idorder =", value, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderNotEqualTo(Integer value) {
            addCriterion("idorder <>", value, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderGreaterThan(Integer value) {
            addCriterion("idorder >", value, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderGreaterThanOrEqualTo(Integer value) {
            addCriterion("idorder >=", value, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderLessThan(Integer value) {
            addCriterion("idorder <", value, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderLessThanOrEqualTo(Integer value) {
            addCriterion("idorder <=", value, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderIn(List<Integer> values) {
            addCriterion("idorder in", values, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderNotIn(List<Integer> values) {
            addCriterion("idorder not in", values, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderBetween(Integer value1, Integer value2) {
            addCriterion("idorder between", value1, value2, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdorderNotBetween(Integer value1, Integer value2) {
            addCriterion("idorder not between", value1, value2, "idorder");
            return (Criteria) this;
        }

        public Criteria andIdproductIsNull() {
            addCriterion("idproduct is null");
            return (Criteria) this;
        }

        public Criteria andIdproductIsNotNull() {
            addCriterion("idproduct is not null");
            return (Criteria) this;
        }

        public Criteria andIdproductEqualTo(Integer value) {
            addCriterion("idproduct =", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductNotEqualTo(Integer value) {
            addCriterion("idproduct <>", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductGreaterThan(Integer value) {
            addCriterion("idproduct >", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductGreaterThanOrEqualTo(Integer value) {
            addCriterion("idproduct >=", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductLessThan(Integer value) {
            addCriterion("idproduct <", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductLessThanOrEqualTo(Integer value) {
            addCriterion("idproduct <=", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductIn(List<Integer> values) {
            addCriterion("idproduct in", values, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductNotIn(List<Integer> values) {
            addCriterion("idproduct not in", values, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductBetween(Integer value1, Integer value2) {
            addCriterion("idproduct between", value1, value2, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductNotBetween(Integer value1, Integer value2) {
            addCriterion("idproduct not between", value1, value2, "idproduct");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andBookdateIsNull() {
            addCriterion("bookdate is null");
            return (Criteria) this;
        }

        public Criteria andBookdateIsNotNull() {
            addCriterion("bookdate is not null");
            return (Criteria) this;
        }

        public Criteria andBookdateEqualTo(Date value) {
            addCriterion("bookdate =", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateNotEqualTo(Date value) {
            addCriterion("bookdate <>", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateGreaterThan(Date value) {
            addCriterion("bookdate >", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateGreaterThanOrEqualTo(Date value) {
            addCriterion("bookdate >=", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateLessThan(Date value) {
            addCriterion("bookdate <", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateLessThanOrEqualTo(Date value) {
            addCriterion("bookdate <=", value, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateIn(List<Date> values) {
            addCriterion("bookdate in", values, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateNotIn(List<Date> values) {
            addCriterion("bookdate not in", values, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateBetween(Date value1, Date value2) {
            addCriterion("bookdate between", value1, value2, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookdateNotBetween(Date value1, Date value2) {
            addCriterion("bookdate not between", value1, value2, "bookdate");
            return (Criteria) this;
        }

        public Criteria andBookpriceIsNull() {
            addCriterion("bookprice is null");
            return (Criteria) this;
        }

        public Criteria andBookpriceIsNotNull() {
            addCriterion("bookprice is not null");
            return (Criteria) this;
        }

        public Criteria andBookpriceEqualTo(Double value) {
            addCriterion("bookprice =", value, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceNotEqualTo(Double value) {
            addCriterion("bookprice <>", value, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceGreaterThan(Double value) {
            addCriterion("bookprice >", value, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("bookprice >=", value, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceLessThan(Double value) {
            addCriterion("bookprice <", value, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceLessThanOrEqualTo(Double value) {
            addCriterion("bookprice <=", value, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceIn(List<Double> values) {
            addCriterion("bookprice in", values, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceNotIn(List<Double> values) {
            addCriterion("bookprice not in", values, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceBetween(Double value1, Double value2) {
            addCriterion("bookprice between", value1, value2, "bookprice");
            return (Criteria) this;
        }

        public Criteria andBookpriceNotBetween(Double value1, Double value2) {
            addCriterion("bookprice not between", value1, value2, "bookprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceIsNull() {
            addCriterion("esticostprice is null");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceIsNotNull() {
            addCriterion("esticostprice is not null");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceEqualTo(Double value) {
            addCriterion("esticostprice =", value, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceNotEqualTo(Double value) {
            addCriterion("esticostprice <>", value, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceGreaterThan(Double value) {
            addCriterion("esticostprice >", value, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("esticostprice >=", value, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceLessThan(Double value) {
            addCriterion("esticostprice <", value, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceLessThanOrEqualTo(Double value) {
            addCriterion("esticostprice <=", value, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceIn(List<Double> values) {
            addCriterion("esticostprice in", values, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceNotIn(List<Double> values) {
            addCriterion("esticostprice not in", values, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceBetween(Double value1, Double value2) {
            addCriterion("esticostprice between", value1, value2, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andEsticostpriceNotBetween(Double value1, Double value2) {
            addCriterion("esticostprice not between", value1, value2, "esticostprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNull() {
            addCriterion("costprice is null");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNotNull() {
            addCriterion("costprice is not null");
            return (Criteria) this;
        }

        public Criteria andCostpriceEqualTo(Double value) {
            addCriterion("costprice =", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotEqualTo(Double value) {
            addCriterion("costprice <>", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThan(Double value) {
            addCriterion("costprice >", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("costprice >=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThan(Double value) {
            addCriterion("costprice <", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThanOrEqualTo(Double value) {
            addCriterion("costprice <=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIn(List<Double> values) {
            addCriterion("costprice in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotIn(List<Double> values) {
            addCriterion("costprice not in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceBetween(Double value1, Double value2) {
            addCriterion("costprice between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotBetween(Double value1, Double value2) {
            addCriterion("costprice not between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andBookrateIsNull() {
            addCriterion("bookrate is null");
            return (Criteria) this;
        }

        public Criteria andBookrateIsNotNull() {
            addCriterion("bookrate is not null");
            return (Criteria) this;
        }

        public Criteria andBookrateEqualTo(Double value) {
            addCriterion("bookrate =", value, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateNotEqualTo(Double value) {
            addCriterion("bookrate <>", value, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateGreaterThan(Double value) {
            addCriterion("bookrate >", value, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateGreaterThanOrEqualTo(Double value) {
            addCriterion("bookrate >=", value, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateLessThan(Double value) {
            addCriterion("bookrate <", value, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateLessThanOrEqualTo(Double value) {
            addCriterion("bookrate <=", value, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateIn(List<Double> values) {
            addCriterion("bookrate in", values, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateNotIn(List<Double> values) {
            addCriterion("bookrate not in", values, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateBetween(Double value1, Double value2) {
            addCriterion("bookrate between", value1, value2, "bookrate");
            return (Criteria) this;
        }

        public Criteria andBookrateNotBetween(Double value1, Double value2) {
            addCriterion("bookrate not between", value1, value2, "bookrate");
            return (Criteria) this;
        }

        public Criteria andCostrateIsNull() {
            addCriterion("costrate is null");
            return (Criteria) this;
        }

        public Criteria andCostrateIsNotNull() {
            addCriterion("costrate is not null");
            return (Criteria) this;
        }

        public Criteria andCostrateEqualTo(Double value) {
            addCriterion("costrate =", value, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateNotEqualTo(Double value) {
            addCriterion("costrate <>", value, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateGreaterThan(Double value) {
            addCriterion("costrate >", value, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateGreaterThanOrEqualTo(Double value) {
            addCriterion("costrate >=", value, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateLessThan(Double value) {
            addCriterion("costrate <", value, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateLessThanOrEqualTo(Double value) {
            addCriterion("costrate <=", value, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateIn(List<Double> values) {
            addCriterion("costrate in", values, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateNotIn(List<Double> values) {
            addCriterion("costrate not in", values, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateBetween(Double value1, Double value2) {
            addCriterion("costrate between", value1, value2, "costrate");
            return (Criteria) this;
        }

        public Criteria andCostrateNotBetween(Double value1, Double value2) {
            addCriterion("costrate not between", value1, value2, "costrate");
            return (Criteria) this;
        }

        public Criteria andProfitIsNull() {
            addCriterion("profit is null");
            return (Criteria) this;
        }

        public Criteria andProfitIsNotNull() {
            addCriterion("profit is not null");
            return (Criteria) this;
        }

        public Criteria andProfitEqualTo(Double value) {
            addCriterion("profit =", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitNotEqualTo(Double value) {
            addCriterion("profit <>", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitGreaterThan(Double value) {
            addCriterion("profit >", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitGreaterThanOrEqualTo(Double value) {
            addCriterion("profit >=", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitLessThan(Double value) {
            addCriterion("profit <", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitLessThanOrEqualTo(Double value) {
            addCriterion("profit <=", value, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitIn(List<Double> values) {
            addCriterion("profit in", values, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitNotIn(List<Double> values) {
            addCriterion("profit not in", values, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitBetween(Double value1, Double value2) {
            addCriterion("profit between", value1, value2, "profit");
            return (Criteria) this;
        }

        public Criteria andProfitNotBetween(Double value1, Double value2) {
            addCriterion("profit not between", value1, value2, "profit");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderdetail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
