package com.junpeng.daigou.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected boolean distinct;
  
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdproductIsNull() {
            addCriterion("idproduct is null");
            return (Criteria) this;
        }

        public Criteria andIdproductIsNotNull() {
            addCriterion("idproduct is not null");
            return (Criteria) this;
        }

        public Criteria andIdproductEqualTo(Integer value) {
            addCriterion("idproduct =", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductNotEqualTo(Integer value) {
            addCriterion("idproduct <>", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductGreaterThan(Integer value) {
            addCriterion("idproduct >", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductGreaterThanOrEqualTo(Integer value) {
            addCriterion("idproduct >=", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductLessThan(Integer value) {
            addCriterion("idproduct <", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductLessThanOrEqualTo(Integer value) {
            addCriterion("idproduct <=", value, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductIn(List<Integer> values) {
            addCriterion("idproduct in", values, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductNotIn(List<Integer> values) {
            addCriterion("idproduct not in", values, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductBetween(Integer value1, Integer value2) {
            addCriterion("idproduct between", value1, value2, "idproduct");
            return (Criteria) this;
        }

        public Criteria andIdproductNotBetween(Integer value1, Integer value2) {
            addCriterion("idproduct not between", value1, value2, "idproduct");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNull() {
            addCriterion("productname is null");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNotNull() {
            addCriterion("productname is not null");
            return (Criteria) this;
        }

        public Criteria andProductnameEqualTo(String value) {
            addCriterion("productname =", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotEqualTo(String value) {
            addCriterion("productname <>", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThan(String value) {
            addCriterion("productname >", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThanOrEqualTo(String value) {
            addCriterion("productname >=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThan(String value) {
            addCriterion("productname <", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThanOrEqualTo(String value) {
            addCriterion("productname <=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLike(String value) {
            addCriterion("productname like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotLike(String value) {
            addCriterion("productname not like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameIn(List<String> values) {
            addCriterion("productname in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotIn(List<String> values) {
            addCriterion("productname not in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameBetween(String value1, String value2) {
            addCriterion("productname between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotBetween(String value1, String value2) {
            addCriterion("productname not between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanIsNull() {
            addCriterion("productnamejapan is null");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanIsNotNull() {
            addCriterion("productnamejapan is not null");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanEqualTo(String value) {
            addCriterion("productnamejapan =", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanNotEqualTo(String value) {
            addCriterion("productnamejapan <>", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanGreaterThan(String value) {
            addCriterion("productnamejapan >", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanGreaterThanOrEqualTo(String value) {
            addCriterion("productnamejapan >=", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanLessThan(String value) {
            addCriterion("productnamejapan <", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanLessThanOrEqualTo(String value) {
            addCriterion("productnamejapan <=", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanLike(String value) {
            addCriterion("productnamejapan like", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanNotLike(String value) {
            addCriterion("productnamejapan not like", value, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanIn(List<String> values) {
            addCriterion("productnamejapan in", values, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanNotIn(List<String> values) {
            addCriterion("productnamejapan not in", values, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanBetween(String value1, String value2) {
            addCriterion("productnamejapan between", value1, value2, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andProductnamejapanNotBetween(String value1, String value2) {
            addCriterion("productnamejapan not between", value1, value2, "productnamejapan");
            return (Criteria) this;
        }

        public Criteria andIdbrandIsNull() {
            addCriterion("idbrand is null");
            return (Criteria) this;
        }

        public Criteria andIdbrandIsNotNull() {
            addCriterion("idbrand is not null");
            return (Criteria) this;
        }

        public Criteria andIdbrandEqualTo(Integer value) {
            addCriterion("idbrand =", value, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandNotEqualTo(Integer value) {
            addCriterion("idbrand <>", value, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandGreaterThan(Integer value) {
            addCriterion("idbrand >", value, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandGreaterThanOrEqualTo(Integer value) {
            addCriterion("idbrand >=", value, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandLessThan(Integer value) {
            addCriterion("idbrand <", value, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandLessThanOrEqualTo(Integer value) {
            addCriterion("idbrand <=", value, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandIn(List<Integer> values) {
            addCriterion("idbrand in", values, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandNotIn(List<Integer> values) {
            addCriterion("idbrand not in", values, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandBetween(Integer value1, Integer value2) {
            addCriterion("idbrand between", value1, value2, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdbrandNotBetween(Integer value1, Integer value2) {
            addCriterion("idbrand not between", value1, value2, "idbrand");
            return (Criteria) this;
        }

        public Criteria andIdcategoryIsNull() {
            addCriterion("idcategory is null");
            return (Criteria) this;
        }

        public Criteria andIdcategoryIsNotNull() {
            addCriterion("idcategory is not null");
            return (Criteria) this;
        }

        public Criteria andIdcategoryEqualTo(Integer value) {
            addCriterion("idcategory =", value, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryNotEqualTo(Integer value) {
            addCriterion("idcategory <>", value, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryGreaterThan(Integer value) {
            addCriterion("idcategory >", value, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("idcategory >=", value, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryLessThan(Integer value) {
            addCriterion("idcategory <", value, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryLessThanOrEqualTo(Integer value) {
            addCriterion("idcategory <=", value, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryIn(List<Integer> values) {
            addCriterion("idcategory in", values, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryNotIn(List<Integer> values) {
            addCriterion("idcategory not in", values, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryBetween(Integer value1, Integer value2) {
            addCriterion("idcategory between", value1, value2, "idcategory");
            return (Criteria) this;
        }

        public Criteria andIdcategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("idcategory not between", value1, value2, "idcategory");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceIsNull() {
            addCriterion("officalprice is null");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceIsNotNull() {
            addCriterion("officalprice is not null");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceEqualTo(Double value) {
            addCriterion("officalprice =", value, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceNotEqualTo(Double value) {
            addCriterion("officalprice <>", value, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceGreaterThan(Double value) {
            addCriterion("officalprice >", value, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("officalprice >=", value, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceLessThan(Double value) {
            addCriterion("officalprice <", value, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceLessThanOrEqualTo(Double value) {
            addCriterion("officalprice <=", value, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceIn(List<Double> values) {
            addCriterion("officalprice in", values, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceNotIn(List<Double> values) {
            addCriterion("officalprice not in", values, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceBetween(Double value1, Double value2) {
            addCriterion("officalprice between", value1, value2, "officalprice");
            return (Criteria) this;
        }

        public Criteria andOfficalpriceNotBetween(Double value1, Double value2) {
            addCriterion("officalprice not between", value1, value2, "officalprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceIsNull() {
            addCriterion("recentlybookprice is null");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceIsNotNull() {
            addCriterion("recentlybookprice is not null");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceEqualTo(Double value) {
            addCriterion("recentlybookprice =", value, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceNotEqualTo(Double value) {
            addCriterion("recentlybookprice <>", value, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceGreaterThan(Double value) {
            addCriterion("recentlybookprice >", value, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("recentlybookprice >=", value, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceLessThan(Double value) {
            addCriterion("recentlybookprice <", value, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceLessThanOrEqualTo(Double value) {
            addCriterion("recentlybookprice <=", value, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceIn(List<Double> values) {
            addCriterion("recentlybookprice in", values, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceNotIn(List<Double> values) {
            addCriterion("recentlybookprice not in", values, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceBetween(Double value1, Double value2) {
            addCriterion("recentlybookprice between", value1, value2, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andRecentlybookpriceNotBetween(Double value1, Double value2) {
            addCriterion("recentlybookprice not between", value1, value2, "recentlybookprice");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingIsNull() {
            addCriterion("iddiscountsetting is null");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingIsNotNull() {
            addCriterion("iddiscountsetting is not null");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingEqualTo(Integer value) {
            addCriterion("iddiscountsetting =", value, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingNotEqualTo(Integer value) {
            addCriterion("iddiscountsetting <>", value, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingGreaterThan(Integer value) {
            addCriterion("iddiscountsetting >", value, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingGreaterThanOrEqualTo(Integer value) {
            addCriterion("iddiscountsetting >=", value, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingLessThan(Integer value) {
            addCriterion("iddiscountsetting <", value, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingLessThanOrEqualTo(Integer value) {
            addCriterion("iddiscountsetting <=", value, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingIn(List<Integer> values) {
            addCriterion("iddiscountsetting in", values, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingNotIn(List<Integer> values) {
            addCriterion("iddiscountsetting not in", values, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingBetween(Integer value1, Integer value2) {
            addCriterion("iddiscountsetting between", value1, value2, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIddiscountsettingNotBetween(Integer value1, Integer value2) {
            addCriterion("iddiscountsetting not between", value1, value2, "iddiscountsetting");
            return (Criteria) this;
        }

        public Criteria andIstaxIsNull() {
            addCriterion("istax is null");
            return (Criteria) this;
        }

        public Criteria andIstaxIsNotNull() {
            addCriterion("istax is not null");
            return (Criteria) this;
        }

        public Criteria andIstaxEqualTo(String value) {
            addCriterion("istax =", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxNotEqualTo(String value) {
            addCriterion("istax <>", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxGreaterThan(String value) {
            addCriterion("istax >", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxGreaterThanOrEqualTo(String value) {
            addCriterion("istax >=", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxLessThan(String value) {
            addCriterion("istax <", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxLessThanOrEqualTo(String value) {
            addCriterion("istax <=", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxLike(String value) {
            addCriterion("istax like", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxNotLike(String value) {
            addCriterion("istax not like", value, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxIn(List<String> values) {
            addCriterion("istax in", values, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxNotIn(List<String> values) {
            addCriterion("istax not in", values, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxBetween(String value1, String value2) {
            addCriterion("istax between", value1, value2, "istax");
            return (Criteria) this;
        }

        public Criteria andIstaxNotBetween(String value1, String value2) {
            addCriterion("istax not between", value1, value2, "istax");
            return (Criteria) this;
        }

        public Criteria andTaxfeeIsNull() {
            addCriterion("taxfee is null");
            return (Criteria) this;
        }

        public Criteria andTaxfeeIsNotNull() {
            addCriterion("taxfee is not null");
            return (Criteria) this;
        }

        public Criteria andTaxfeeEqualTo(Double value) {
            addCriterion("taxfee =", value, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeNotEqualTo(Double value) {
            addCriterion("taxfee <>", value, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeGreaterThan(Double value) {
            addCriterion("taxfee >", value, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeGreaterThanOrEqualTo(Double value) {
            addCriterion("taxfee >=", value, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeLessThan(Double value) {
            addCriterion("taxfee <", value, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeLessThanOrEqualTo(Double value) {
            addCriterion("taxfee <=", value, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeIn(List<Double> values) {
            addCriterion("taxfee in", values, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeNotIn(List<Double> values) {
            addCriterion("taxfee not in", values, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeBetween(Double value1, Double value2) {
            addCriterion("taxfee between", value1, value2, "taxfee");
            return (Criteria) this;
        }

        public Criteria andTaxfeeNotBetween(Double value1, Double value2) {
            addCriterion("taxfee not between", value1, value2, "taxfee");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("discount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("discount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(Double value) {
            addCriterion("discount =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(Double value) {
            addCriterion("discount <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(Double value) {
            addCriterion("discount >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(Double value) {
            addCriterion("discount >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(Double value) {
            addCriterion("discount <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(Double value) {
            addCriterion("discount <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<Double> values) {
            addCriterion("discount in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<Double> values) {
            addCriterion("discount not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(Double value1, Double value2) {
            addCriterion("discount between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(Double value1, Double value2) {
            addCriterion("discount not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNull() {
            addCriterion("costPrice is null");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNotNull() {
            addCriterion("costPrice is not null");
            return (Criteria) this;
        }

        public Criteria andCostpriceEqualTo(Double value) {
            addCriterion("costPrice =", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotEqualTo(Double value) {
            addCriterion("costPrice <>", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThan(Double value) {
            addCriterion("costPrice >", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("costPrice >=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThan(Double value) {
            addCriterion("costPrice <", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThanOrEqualTo(Double value) {
            addCriterion("costPrice <=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIn(List<Double> values) {
            addCriterion("costPrice in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotIn(List<Double> values) {
            addCriterion("costPrice not in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceBetween(Double value1, Double value2) {
            addCriterion("costPrice between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotBetween(Double value1, Double value2) {
            addCriterion("costPrice not between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyIsNull() {
            addCriterion("costPriceJpy is null");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyIsNotNull() {
            addCriterion("costPriceJpy is not null");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyEqualTo(Double value) {
            addCriterion("costPriceJpy =", value, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyNotEqualTo(Double value) {
            addCriterion("costPriceJpy <>", value, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyGreaterThan(Double value) {
            addCriterion("costPriceJpy >", value, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyGreaterThanOrEqualTo(Double value) {
            addCriterion("costPriceJpy >=", value, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyLessThan(Double value) {
            addCriterion("costPriceJpy <", value, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyLessThanOrEqualTo(Double value) {
            addCriterion("costPriceJpy <=", value, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyIn(List<Double> values) {
            addCriterion("costPriceJpy in", values, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyNotIn(List<Double> values) {
            addCriterion("costPriceJpy not in", values, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyBetween(Double value1, Double value2) {
            addCriterion("costPriceJpy between", value1, value2, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andCostpricejpyNotBetween(Double value1, Double value2) {
            addCriterion("costPriceJpy not between", value1, value2, "costpricejpy");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNull() {
            addCriterion("saleprice is null");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNotNull() {
            addCriterion("saleprice is not null");
            return (Criteria) this;
        }

        public Criteria andSalepriceEqualTo(Double value) {
            addCriterion("saleprice =", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotEqualTo(Double value) {
            addCriterion("saleprice <>", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThan(Double value) {
            addCriterion("saleprice >", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThanOrEqualTo(Double value) {
            addCriterion("saleprice >=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThan(Double value) {
            addCriterion("saleprice <", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThanOrEqualTo(Double value) {
            addCriterion("saleprice <=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceIn(List<Double> values) {
            addCriterion("saleprice in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotIn(List<Double> values) {
            addCriterion("saleprice not in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceBetween(Double value1, Double value2) {
            addCriterion("saleprice between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotBetween(Double value1, Double value2) {
            addCriterion("saleprice not between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("createuser is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("createuser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("createuser =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("createuser <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("createuser >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("createuser >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("createuser <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("createuser <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("createuser like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("createuser not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("createuser in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("createuser not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("createuser between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("createuser not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("updateuser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("updateuser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("updateuser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("updateuser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("updateuser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("updateuser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("updateuser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("updateuser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("updateuser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("updateuser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("updateuser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("updateuser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("updateuser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("updateuser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNull() {
            addCriterion("isactive is null");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNotNull() {
            addCriterion("isactive is not null");
            return (Criteria) this;
        }

        public Criteria andIsactiveEqualTo(String value) {
            addCriterion("isactive =", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotEqualTo(String value) {
            addCriterion("isactive <>", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThan(String value) {
            addCriterion("isactive >", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThanOrEqualTo(String value) {
            addCriterion("isactive >=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThan(String value) {
            addCriterion("isactive <", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThanOrEqualTo(String value) {
            addCriterion("isactive <=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLike(String value) {
            addCriterion("isactive like", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotLike(String value) {
            addCriterion("isactive not like", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveIn(List<String> values) {
            addCriterion("isactive in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotIn(List<String> values) {
            addCriterion("isactive not in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveBetween(String value1, String value2) {
            addCriterion("isactive between", value1, value2, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotBetween(String value1, String value2) {
            addCriterion("isactive not between", value1, value2, "isactive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}