package com.junpeng.daigou.model;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.idproduct
     *
     * @mbggenerated
     */
    private Integer idproduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productname
     *
     * @mbggenerated
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productnamejapan
     *
     * @mbggenerated
     */
    private String productnamejapan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.idbrand
     *
     * @mbggenerated
     */
    private Integer idbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.idcategory
     *
     * @mbggenerated
     */
    private Integer idcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.officalprice
     *
     * @mbggenerated
     */
    private Double officalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.recentlybookprice
     *
     * @mbggenerated
     */
    private Double recentlybookprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.iddiscountsetting
     *
     * @mbggenerated
     */
    private Integer iddiscountsetting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.istax
     *
     * @mbggenerated
     */
    private String istax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.taxfee
     *
     * @mbggenerated
     */
    private Double taxfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discount
     *
     * @mbggenerated
     */
    private Double discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.costPrice
     *
     * @mbggenerated
     */
    private Double costprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.costPriceJpy
     *
     * @mbggenerated
     */
    private Double costpricejpy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.saleprice
     *
     * @mbggenerated
     */
    private Double saleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createuser
     *
     * @mbggenerated
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updateuser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.isactive
     *
     * @mbggenerated
     */
    private String isactive;
    
    private String brandname;
    private String categoryname;
    
    private String discountsettingname;
    private String discountsettingcomment;

    public String getBrandname() {
		return brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	public String getCategoryname() {
		return categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.idproduct
     *
     * @return the value of product.idproduct
     *
     * @mbggenerated
     */
    public Integer getIdproduct() {
        return idproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.idproduct
     *
     * @param idproduct the value for product.idproduct
     *
     * @mbggenerated
     */
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productname
     *
     * @return the value of product.productname
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productname
     *
     * @param productname the value for product.productname
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productnamejapan
     *
     * @return the value of product.productnamejapan
     *
     * @mbggenerated
     */
    public String getProductnamejapan() {
        return productnamejapan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productnamejapan
     *
     * @param productnamejapan the value for product.productnamejapan
     *
     * @mbggenerated
     */
    public void setProductnamejapan(String productnamejapan) {
        this.productnamejapan = productnamejapan == null ? null : productnamejapan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.idbrand
     *
     * @return the value of product.idbrand
     *
     * @mbggenerated
     */
    public Integer getIdbrand() {
        return idbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.idbrand
     *
     * @param idbrand the value for product.idbrand
     *
     * @mbggenerated
     */
    public void setIdbrand(Integer idbrand) {
        this.idbrand = idbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.idcategory
     *
     * @return the value of product.idcategory
     *
     * @mbggenerated
     */
    public Integer getIdcategory() {
        return idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.idcategory
     *
     * @param idcategory the value for product.idcategory
     *
     * @mbggenerated
     */
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.officalprice
     *
     * @return the value of product.officalprice
     *
     * @mbggenerated
     */
    public Double getOfficalprice() {
        return officalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.officalprice
     *
     * @param officalprice the value for product.officalprice
     *
     * @mbggenerated
     */
    public void setOfficalprice(Double officalprice) {
        this.officalprice = officalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.recentlybookprice
     *
     * @return the value of product.recentlybookprice
     *
     * @mbggenerated
     */
    public Double getRecentlybookprice() {
        return recentlybookprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.recentlybookprice
     *
     * @param recentlybookprice the value for product.recentlybookprice
     *
     * @mbggenerated
     */
    public void setRecentlybookprice(Double recentlybookprice) {
        this.recentlybookprice = recentlybookprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.iddiscountsetting
     *
     * @return the value of product.iddiscountsetting
     *
     * @mbggenerated
     */
    public Integer getIddiscountsetting() {
        return iddiscountsetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.iddiscountsetting
     *
     * @param iddiscountsetting the value for product.iddiscountsetting
     *
     * @mbggenerated
     */
    public void setIddiscountsetting(Integer iddiscountsetting) {
        this.iddiscountsetting = iddiscountsetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.istax
     *
     * @return the value of product.istax
     *
     * @mbggenerated
     */
    public String getIstax() {
        return istax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.istax
     *
     * @param istax the value for product.istax
     *
     * @mbggenerated
     */
    public void setIstax(String istax) {
        this.istax = istax == null ? null : istax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.taxfee
     *
     * @return the value of product.taxfee
     *
     * @mbggenerated
     */
    public Double getTaxfee() {
        return taxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.taxfee
     *
     * @param taxfee the value for product.taxfee
     *
     * @mbggenerated
     */
    public void setTaxfee(Double taxfee) {
        this.taxfee = taxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discount
     *
     * @return the value of product.discount
     *
     * @mbggenerated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discount
     *
     * @param discount the value for product.discount
     *
     * @mbggenerated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.costPrice
     *
     * @return the value of product.costPrice
     *
     * @mbggenerated
     */
    public Double getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.costPrice
     *
     * @param costprice the value for product.costPrice
     *
     * @mbggenerated
     */
    public void setCostprice(Double costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.costPriceJpy
     *
     * @return the value of product.costPriceJpy
     *
     * @mbggenerated
     */
    public Double getCostpricejpy() {
        return costpricejpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.costPriceJpy
     *
     * @param costpricejpy the value for product.costPriceJpy
     *
     * @mbggenerated
     */
    public void setCostpricejpy(Double costpricejpy) {
        this.costpricejpy = costpricejpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.saleprice
     *
     * @return the value of product.saleprice
     *
     * @mbggenerated
     */
    public Double getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.saleprice
     *
     * @param saleprice the value for product.saleprice
     *
     * @mbggenerated
     */
    public void setSaleprice(Double saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createtime
     *
     * @return the value of product.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createtime
     *
     * @param createtime the value for product.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createuser
     *
     * @return the value of product.createuser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createuser
     *
     * @param createuser the value for product.createuser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updatetime
     *
     * @return the value of product.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updatetime
     *
     * @param updatetime the value for product.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updateuser
     *
     * @return the value of product.updateuser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updateuser
     *
     * @param updateuser the value for product.updateuser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.isactive
     *
     * @return the value of product.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.isactive
     *
     * @param isactive the value for product.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

	public String getDiscountsettingname() {
		return discountsettingname;
	}

	public void setDiscountsettingname(String discountsettingname) {
		this.discountsettingname = discountsettingname;
	}

	public String getDiscountsettingcomment() {
		return discountsettingcomment;
	}

	public void setDiscountsettingcomment(String discountsettingcomment) {
		this.discountsettingcomment = discountsettingcomment;
	}
    
    
}