package com.junpeng.daigou.model;

import java.util.Date;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.idpurchase
     *
     * @mbggenerated
     */
    private Integer idpurchase;

    private Integer idmarket;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.idbrand
     *
     * @mbggenerated
     */
    private Integer idbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.totalprice
     *
     * @mbggenerated
     */
    private Double totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchasedate
     *
     * @mbggenerated
     */
    private Date purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchasetype
     *
     * @mbggenerated
     */
    private String purchasetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.cardno
     *
     * @mbggenerated
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.usescore
     *
     * @mbggenerated
     */
    private Integer usescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.rate
     *
     * @mbggenerated
     */
    private Double rate;

    private String createuser;

    private Date createdate;

    private String updateuser;

    private Date updatedate;

    private String status;

    private String isactive;
	
    private String brandname;
    
    private String marketname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.idpurchase
     *
     * @return the value of purchase.idpurchase
     *
     * @mbggenerated
     */
    public Integer getIdpurchase() {
        return idpurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.idpurchase
     *
     * @param idpurchase the value for purchase.idpurchase
     *
     * @mbggenerated
     */
    public void setIdpurchase(Integer idpurchase) {
        this.idpurchase = idpurchase;
    }
    public Integer getIdmarket() {
        return idmarket;
    }

    public void setIdmarket(Integer idmarket) {
        this.idmarket = idmarket;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.idbrand
     *
     * @return the value of purchase.idbrand
     *
     * @mbggenerated
     */
    public Integer getIdbrand() {
        return idbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.idbrand
     *
     * @param idbrand the value for purchase.idbrand
     *
     * @mbggenerated
     */
    public void setIdbrand(Integer idbrand) {
        this.idbrand = idbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.totalprice
     *
     * @return the value of purchase.totalprice
     *
     * @mbggenerated
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.totalprice
     *
     * @param totalprice the value for purchase.totalprice
     *
     * @mbggenerated
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchasedate
     *
     * @return the value of purchase.purchasedate
     *
     * @mbggenerated
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchasedate
     *
     * @param purchasedate the value for purchase.purchasedate
     *
     * @mbggenerated
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchasetype
     *
     * @return the value of purchase.purchasetype
     *
     * @mbggenerated
     */
    public String getPurchasetype() {
        return purchasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchasetype
     *
     * @param purchasetype the value for purchase.purchasetype
     *
     * @mbggenerated
     */
    public void setPurchasetype(String purchasetype) {
        this.purchasetype = purchasetype == null ? null : purchasetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.cardno
     *
     * @return the value of purchase.cardno
     *
     * @mbggenerated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.cardno
     *
     * @param cardno the value for purchase.cardno
     *
     * @mbggenerated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.usescore
     *
     * @return the value of purchase.usescore
     *
     * @mbggenerated
     */
    public Integer getUsescore() {
        return usescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.usescore
     *
     * @param usescore the value for purchase.usescore
     *
     * @mbggenerated
     */
    public void setUsescore(Integer usescore) {
        this.usescore = usescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.rate
     *
     * @return the value of purchase.rate
     *
     * @mbggenerated
     */
    public Double getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.rate
     *
     * @param rate the value for purchase.rate
     *
     * @mbggenerated
     */
    public void setRate(Double rate) {
        this.rate = rate;
    }

	public String getBrandname() {
		return brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}
   public String getCreateuser() {
        return createuser;
    }

    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public String getUpdateuser() {
        return updateuser;
    }

    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIsactive() {
        return isactive;
    }

    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

	public String getMarketname() {
		return marketname;
	}

	public void setMarketname(String marketname) {
		this.marketname = marketname;
	}  
    
}