package com.junpeng.daigou.model;

public class PurchaseDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.idpurchasedetail
     *
     * @mbggenerated
     */
    private Integer idpurchasedetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.idpurchase
     *
     * @mbggenerated
     */
    private Integer idpurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.idproduct
     *
     * @mbggenerated
     */
    private Integer idproduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.singleprice
     *
     * @mbggenerated
     */
    private Double singleprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.sumprice
     *
     * @mbggenerated
     */
    private Double sumprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasedetail.getscore
     *
     * @mbggenerated
     */
    private Integer getscore;
    
    private String productname;
    private Double rate;
    
    private Integer idbrand;
    private String brandName;
    
    private Integer idmarket;
    private String marketName;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.idpurchasedetail
     *
     * @return the value of purchasedetail.idpurchasedetail
     *
     * @mbggenerated
     */
    public Integer getIdpurchasedetail() {
        return idpurchasedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.idpurchasedetail
     *
     * @param idpurchasedetail the value for purchasedetail.idpurchasedetail
     *
     * @mbggenerated
     */
    public void setIdpurchasedetail(Integer idpurchasedetail) {
        this.idpurchasedetail = idpurchasedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.idpurchase
     *
     * @return the value of purchasedetail.idpurchase
     *
     * @mbggenerated
     */
    public Integer getIdpurchase() {
        return idpurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.idpurchase
     *
     * @param idpurchase the value for purchasedetail.idpurchase
     *
     * @mbggenerated
     */
    public void setIdpurchase(Integer idpurchase) {
        this.idpurchase = idpurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.idproduct
     *
     * @return the value of purchasedetail.idproduct
     *
     * @mbggenerated
     */
    public Integer getIdproduct() {
        return idproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.idproduct
     *
     * @param idproduct the value for purchasedetail.idproduct
     *
     * @mbggenerated
     */
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.count
     *
     * @return the value of purchasedetail.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.count
     *
     * @param count the value for purchasedetail.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.singleprice
     *
     * @return the value of purchasedetail.singleprice
     *
     * @mbggenerated
     */
    public Double getSingleprice() {
        return singleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.singleprice
     *
     * @param singleprice the value for purchasedetail.singleprice
     *
     * @mbggenerated
     */
    public void setSingleprice(Double singleprice) {
        this.singleprice = singleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.sumprice
     *
     * @return the value of purchasedetail.sumprice
     *
     * @mbggenerated
     */
    public Double getSumprice() {
        return sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.sumprice
     *
     * @param sumprice the value for purchasedetail.sumprice
     *
     * @mbggenerated
     */
    public void setSumprice(Double sumprice) {
        this.sumprice = sumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasedetail.getscore
     *
     * @return the value of purchasedetail.getscore
     *
     * @mbggenerated
     */
    public Integer getGetscore() {
        return getscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasedetail.getscore
     *
     * @param getscore the value for purchasedetail.getscore
     *
     * @mbggenerated
     */
    public void setGetscore(Integer getscore) {
        this.getscore = getscore;
    }

	public String getProductname() {
		return productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public Double getRate() {
		return rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Integer getIdbrand() {
		return idbrand;
	}

	public void setIdbrand(Integer idbrand) {
		this.idbrand = idbrand;
	}

	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public Integer getIdmarket() {
		return idmarket;
	}

	public void setIdmarket(Integer idmarket) {
		this.idmarket = idmarket;
	}

	public String getMarketName() {
		return marketName;
	}

	public void setMarketName(String marketName) {
		this.marketName = marketName;
	}
}