package com.junpeng.daigou.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public SystemSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdsystemsettingIsNull() {
            addCriterion("idsystemsetting is null");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingIsNotNull() {
            addCriterion("idsystemsetting is not null");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingEqualTo(Integer value) {
            addCriterion("idsystemsetting =", value, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingNotEqualTo(Integer value) {
            addCriterion("idsystemsetting <>", value, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingGreaterThan(Integer value) {
            addCriterion("idsystemsetting >", value, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingGreaterThanOrEqualTo(Integer value) {
            addCriterion("idsystemsetting >=", value, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingLessThan(Integer value) {
            addCriterion("idsystemsetting <", value, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingLessThanOrEqualTo(Integer value) {
            addCriterion("idsystemsetting <=", value, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingIn(List<Integer> values) {
            addCriterion("idsystemsetting in", values, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingNotIn(List<Integer> values) {
            addCriterion("idsystemsetting not in", values, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingBetween(Integer value1, Integer value2) {
            addCriterion("idsystemsetting between", value1, value2, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andIdsystemsettingNotBetween(Integer value1, Integer value2) {
            addCriterion("idsystemsetting not between", value1, value2, "idsystemsetting");
            return (Criteria) this;
        }

        public Criteria andPropertiynameIsNull() {
            addCriterion("propertiyname is null");
            return (Criteria) this;
        }

        public Criteria andPropertiynameIsNotNull() {
            addCriterion("propertiyname is not null");
            return (Criteria) this;
        }

        public Criteria andPropertiynameEqualTo(String value) {
            addCriterion("propertiyname =", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameNotEqualTo(String value) {
            addCriterion("propertiyname <>", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameGreaterThan(String value) {
            addCriterion("propertiyname >", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameGreaterThanOrEqualTo(String value) {
            addCriterion("propertiyname >=", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameLessThan(String value) {
            addCriterion("propertiyname <", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameLessThanOrEqualTo(String value) {
            addCriterion("propertiyname <=", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameLike(String value) {
            addCriterion("propertiyname like", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameNotLike(String value) {
            addCriterion("propertiyname not like", value, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameIn(List<String> values) {
            addCriterion("propertiyname in", values, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameNotIn(List<String> values) {
            addCriterion("propertiyname not in", values, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameBetween(String value1, String value2) {
            addCriterion("propertiyname between", value1, value2, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiynameNotBetween(String value1, String value2) {
            addCriterion("propertiyname not between", value1, value2, "propertiyname");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueIsNull() {
            addCriterion("propertiyvalue is null");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueIsNotNull() {
            addCriterion("propertiyvalue is not null");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueEqualTo(String value) {
            addCriterion("propertiyvalue =", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueNotEqualTo(String value) {
            addCriterion("propertiyvalue <>", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueGreaterThan(String value) {
            addCriterion("propertiyvalue >", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueGreaterThanOrEqualTo(String value) {
            addCriterion("propertiyvalue >=", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueLessThan(String value) {
            addCriterion("propertiyvalue <", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueLessThanOrEqualTo(String value) {
            addCriterion("propertiyvalue <=", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueLike(String value) {
            addCriterion("propertiyvalue like", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueNotLike(String value) {
            addCriterion("propertiyvalue not like", value, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueIn(List<String> values) {
            addCriterion("propertiyvalue in", values, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueNotIn(List<String> values) {
            addCriterion("propertiyvalue not in", values, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueBetween(String value1, String value2) {
            addCriterion("propertiyvalue between", value1, value2, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertiyvalueNotBetween(String value1, String value2) {
            addCriterion("propertiyvalue not between", value1, value2, "propertiyvalue");
            return (Criteria) this;
        }

        public Criteria andSetdateIsNull() {
            addCriterion("setdate is null");
            return (Criteria) this;
        }

        public Criteria andSetdateIsNotNull() {
            addCriterion("setdate is not null");
            return (Criteria) this;
        }

        public Criteria andSetdateEqualTo(Date value) {
            addCriterion("setdate =", value, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateNotEqualTo(Date value) {
            addCriterion("setdate <>", value, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateGreaterThan(Date value) {
            addCriterion("setdate >", value, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateGreaterThanOrEqualTo(Date value) {
            addCriterion("setdate >=", value, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateLessThan(Date value) {
            addCriterion("setdate <", value, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateLessThanOrEqualTo(Date value) {
            addCriterion("setdate <=", value, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateIn(List<Date> values) {
            addCriterion("setdate in", values, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateNotIn(List<Date> values) {
            addCriterion("setdate not in", values, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateBetween(Date value1, Date value2) {
            addCriterion("setdate between", value1, value2, "setdate");
            return (Criteria) this;
        }

        public Criteria andSetdateNotBetween(Date value1, Date value2) {
            addCriterion("setdate not between", value1, value2, "setdate");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNull() {
            addCriterion("isactive is null");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNotNull() {
            addCriterion("isactive is not null");
            return (Criteria) this;
        }

        public Criteria andIsactiveEqualTo(String value) {
            addCriterion("isactive =", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotEqualTo(String value) {
            addCriterion("isactive <>", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThan(String value) {
            addCriterion("isactive >", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThanOrEqualTo(String value) {
            addCriterion("isactive >=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThan(String value) {
            addCriterion("isactive <", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThanOrEqualTo(String value) {
            addCriterion("isactive <=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLike(String value) {
            addCriterion("isactive like", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotLike(String value) {
            addCriterion("isactive not like", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveIn(List<String> values) {
            addCriterion("isactive in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotIn(List<String> values) {
            addCriterion("isactive not in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveBetween(String value1, String value2) {
            addCriterion("isactive between", value1, value2, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotBetween(String value1, String value2) {
            addCriterion("isactive not between", value1, value2, "isactive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table systemsetting
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table systemsetting
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}