package com.junpeng.daigou.model;

import java.util.Date;

public class SystemSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemsetting.idsystemsetting
     *
     * @mbggenerated
     */
    private Integer idsystemsetting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemsetting.propertiyname
     *
     * @mbggenerated
     */
    private String propertiyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemsetting.propertiyvalue
     *
     * @mbggenerated
     */
    private String propertiyvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemsetting.setdate
     *
     * @mbggenerated
     */
    private Date setdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemsetting.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemsetting.idsystemsetting
     *
     * @return the value of systemsetting.idsystemsetting
     *
     * @mbggenerated
     */
    public Integer getIdsystemsetting() {
        return idsystemsetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemsetting.idsystemsetting
     *
     * @param idsystemsetting the value for systemsetting.idsystemsetting
     *
     * @mbggenerated
     */
    public void setIdsystemsetting(Integer idsystemsetting) {
        this.idsystemsetting = idsystemsetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemsetting.propertiyname
     *
     * @return the value of systemsetting.propertiyname
     *
     * @mbggenerated
     */
    public String getPropertiyname() {
        return propertiyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemsetting.propertiyname
     *
     * @param propertiyname the value for systemsetting.propertiyname
     *
     * @mbggenerated
     */
    public void setPropertiyname(String propertiyname) {
        this.propertiyname = propertiyname == null ? null : propertiyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemsetting.propertiyvalue
     *
     * @return the value of systemsetting.propertiyvalue
     *
     * @mbggenerated
     */
    public String getPropertiyvalue() {
        return propertiyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemsetting.propertiyvalue
     *
     * @param propertiyvalue the value for systemsetting.propertiyvalue
     *
     * @mbggenerated
     */
    public void setPropertiyvalue(String propertiyvalue) {
        this.propertiyvalue = propertiyvalue == null ? null : propertiyvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemsetting.setdate
     *
     * @return the value of systemsetting.setdate
     *
     * @mbggenerated
     */
    public Date getSetdate() {
        return setdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemsetting.setdate
     *
     * @param setdate the value for systemsetting.setdate
     *
     * @mbggenerated
     */
    public void setSetdate(Date setdate) {
        this.setdate = setdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemsetting.isactive
     *
     * @return the value of systemsetting.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemsetting.isactive
     *
     * @param isactive the value for systemsetting.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }
}